export class CensoTributarioModel{
	constructor(
        public Fecha: Date,
        public Municipio: String,
        public Area: Number,
        public Manzana: Number,
        public Casa: Number,
        //Informacion_Propietario
        public Propieratio_Nombre: String,
        public Propieratio_Apellido: String,
        public Tipo_Persona: String,
        public Tipo_Identificacion: String,
        public Indentificacion: Number,
        public DV: Number,
        public Direccion_Propietario: String,
        public Barrio_Propietario: String,
        public Genero: String,
        public Telefono_Propietario: Number,
        public Celular_Propietario: Number,
        public Email_Propietario: String,
        //Informacion_Establecimeinto
        public Nombre_Establecimiento: String,
        public Registrado_en_Alcaldia: String,
        public Direccion_Establecimiento: String,
        public Numero_Registro: Number,
        public Barrio_Establecimiento: String,
        public Telefono_Establecimiento: Number,
        public Celular_Establecimiento: Number,
        public Email_Establecimiento: String,
        public Cantidad_Sucursales: Number,
        public Mayorista: String,
        public Horario_Atencion: String,
        public Contribuyente: String,
        public Regimen: String,
        public Libros_Contables: String,
        public Registro_CamaraYComercio: String,
        public Promedio_Ingreso_Mensual: Number,
        public Numero_Matricula: String,
        public Fecha_Matricula: Date,
        public Tipo_Predio: String,
        public Propiedad: String,
        public Sector: String,
        public Actividad_Desarrollada: String,
        public Numero_Empleados: Number,
        public Codigo_Principal: String,
        public Codigo_Otras_1: String,
        public Codigo_Otras_2: String,
        public Codigo_Otras_3: String,
        public Avisos_Y_Tableros: String,
        public Descripcion_Actividad: String,
        public Pago_Al_Dia: String,
        public Ultimo_Anio_Declarado: Number,
        public Uso_Suelo: String,
        //Juegos
        public Nombre_Juegos_1: String,
        public Cantidad_Juegos_1: Number,
        public Nombre_Juegos_2: String,
        public Cantidad_Juegos_2: Number,
        public Nombre_Juegos_3: String,
        public Cantidad_Juegos_3: Number,
        //Documentos Anexos
        public Rut_Anexo: String,
        public Camara_Y_Comercio_Anexo: String,
        public Fotocopia_Cedula_Anexo: String,
        public Ultimo_Pago_Anexo: String,
        public Formulario_Inscripcion_Anexo: String,
        public Fotocopia_IPU_Anexo: String,
         //Observaciones
        public Observaciones: String,
        //Estado Entrevista
        public Primera_Visita: String,
        public Visita_Fecha: Date,
        public Segunda_Visita: String,
         //Persona Responsable Del Establecimiento
        public Nombre_Responsable_Establecimiento: String,
        public Identificacion_Responsable_Establecimiento: Number,
        public Cargo__Responsable_Establecimiento: String,
        public Firma__Responsable_Establecimiento: String,
        //Persona Responsable De La Encuesta
        public Nombre_Responsable_Ensuesta: String,
        public Indentificacion_Responsable_Ensuesta: Number,
        public Cargo_Responsable_Ensuesta: String,
        public Firma_Responsable_Ensuesta: String,
        //Auditoria
        public Usuario_Creacion: String,
        public Fecha_Creacion: Date,
        public Usuario_Cambio: String,
        public Fecha_Cambio: Date,
        //Estado
        public Estado_Censo: String,
	){}
}